version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro #ro makes it read only for the container

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=e28ea86b3723c5afb3e68a74c4b4cd36d120b3c152bed6c88e8e7cb52267163f
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=999

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: